version: "3.9"

services:
  postgis:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./green_tripdata_2019-09.csv:/home/green_tripdata_2019-09.csv
      - ./taxi+_zone_lookup.csv:/home/taxi+_zone_lookup.csv
    environment:
      POSTGRES_USER: ${POSTGRES_USER-dbuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}
      POSTGRES_DB: ${POSTGRES_DB-postgres}
    ports:
      - 5433:5432
    networks:
      - default

volumes:
  pgdata:
    driver: local

networks:
  default:
    driver: bridge